### ISSUE TITLE
It's better to refactor onPress not to be used directly

### ISSUE THREAD

**Issue by knyaseff** [Hardy1207/ReactNativeFirst#9]
Example:

const doSomething = () => console.log("hello");
Button onPress={doSomething} 

https://github.com/Hardy1207/ReactNativeFirst/blob/ec1c74cb0b6a02dee49b41c434dc9b7d1dcf5a90/Native-client/src/views/screens/HomeScreen.js#L13

**Comment by Hardy1207** [comment]
Fixed
